config/routes.rb
Rails.application.routes.draw do
  resources :pets
  resources :appointments
  root to: 'visitors#index'
  devise_for :users, skip: :registrations
  resources :users
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :pet
  belongs_to :customer, -> {where role: User.roles[:customer]}, :class_name => 'User', primary_key: :id, foreign_key: 'customer_id'
  belongs_to :doctor, -> {where role: User.roles[:doctor]}, :class_name => 'User', :foreign_key => :user_id
  validates :date_of_visit, presence: true
  validate :not_past_date

  def not_past_date
    if self.date_of_visit < Date.today
      errors.add(:date, 'not in past')
    else
      begin
        Date.parse(self.date_of_visit.to_s)
      rescue ArgumentError
        errors.add(:date, 'should be valid')
      end
    end
  end
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :customer, -> {where role: 'customer' }, :class_name => 'User', :primary_key => :id, :foreign_key => :user_id
  has_one :appointment

  validates :name_of_pet, presence: true
  validates :breed, presence: true
  validates :age, presence: true
  validates :weight, presence: true
  validates :date_of_last_visit, presence: true, :on => :update
  validates :name_of_pet, length: { maximum: 35 }
  validates :breed, length: { maximum: 35 }
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:customer, :doctor, :admin, :receptionist]
  after_initialize :set_default_role, :if => :new_record?
  has_many :pets
  has_many :appointments

  validates :name, presence: true
  validates :name, length: { maximum: 35 }
  validates :zip, length: { maximum: 5 }
  validates :years_in_practice, :numericality => {:greater_than => 0, :less_than_or_equal_to => 100}, if: 'years_in_practice.present?'
  def set_default_role
    self.role ||= :customer
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
    @customer = @appointment.customer
    @pet = @appointment.pet
  end

  # POST /appointments
  # POST /appointments.json
  def create
    ActiveRecord::Base.transaction do
      @appointment = Appointment.new(appointment_params)
      customer = User.new
      customer.name = params["customer"]["name"]
      customer.email = params["customer"]["email"]
      customer.password = params["customer"]["password"]
      customer.password_confirmation = params["customer"]["confirm_password"]
      customer.save!
      @appointment.customer = customer
      pet = Pet.new
      pet.name_of_pet = params["pet"]["name_of_pet"]
      pet.type_of_pet = params["pet"]["type_of_pet"]
      pet.breed = params["pet"]["breed"]
      pet.age = params["pet"]["age"]
      pet.weight = params["pet"]["weight"]
      pet.customer = customer
      pet.save!
      @appointment.pet = pet
      respond_to do |format|
        if @appointment.save
          format.html { redirect_to appointments_url, notice: 'Appointment was successfully created.' }
          format.json { render :show, status: :created, location: @appointment }
        else
          format.html { render :new }
          format.json { render json: @appointment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointments_url, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date_of_visit, :pet_id, :user_id, :reminder_of_appointment, :reason_for_visit)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = if current_user.customer?
              current_user.pets
            else
              Pet.where(:id => current_user.appointments.map(&:pet_id))
            end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pets_path, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pets_path, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name_of_pet, :type_of_pet, :breed, :age, :weight, :date_of_last_visit)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all.where.not(:role => [User.roles['customer'], User.roles['receptionist']])
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.admin?
      redirect_to users_path
    elsif current_user.receptionist?
      redirect_to appointments_path
    elsif current_user.doctor?
      redirect_to pets_path
    elsif current_user.customer?
      redirect_to pets_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_visit %><br>
    <%= f.date_select :date_of_visit %>
  </div>
    <hr/>
  <% if current_user.receptionist? %>
      <div class="field">
        <%= f.label 'Customer' %><br>
        <%= fields_for :customer do |customer_fields| %>
            <div class="field">
                <%= customer_fields.label :name %><br>
                <%= customer_fields.text_field :name, class: "form-control" %>
            </div>
            <div class="field">
                <%= customer_fields.label :email %><br>
                <%= customer_fields.email_field :email, class: "form-control" %>
            </div>
            <div class="field">
              <%= customer_fields.label :password %><br>
              <%= customer_fields.password_field :password, class: "form-control" %>
            </div>
            <div class="field">
              <%= customer_fields.label :confirm_password %><br>
              <%= customer_fields.password_field :confirm_password, class: "form-control" %>
            </div>
        <% end %>
      </div>
  <% end %>
  <hr/>
  <div class="field">
    <%= f.label 'Pet' %><br>
    <%= fields_for :pet do |pet_fields| %>
        <% if current_user.receptionist? %>
            <div class="field">
              <%= pet_fields.label :name_of_pet %><br>
              <%= pet_fields.text_field :name_of_pet, class: "form-control" %>
            </div>
            <div class="field">
              <%= pet_fields.label :type_of_pet %><br>
              <%= pet_fields.select(:type_of_pet, ['dog', 'cat', 'bird'], class: "form-control") %>
            </div>
            <div class="field">
              <%= pet_fields.label :breed %><br>
              <%= pet_fields.text_field :breed, class: "form-control" %>
            </div>
            <div class="field">
              <%= pet_fields.label :age %><br>
              <%= pet_fields.number_field :age, class: "form-control" %>
            </div>
            <div class="field">
              <%= pet_fields.label :weight %><br>
              <%= pet_fields.number_field :weight, class: "form-control" %>
            </div>
        <% else %>
            <div class="field">
              <%= pet_fields.label :date_of_last_visit %><br>
              <%= pet_fields.date_select :date_of_last_visit %>
            </div>
        <% end %>
    <% end %>
  </div>
  <% if current_user.receptionist? %>
      <div class="field">
        <%= f.label 'Doctor' %><br>
        <%= collection_select(:appointment, :user_id, User.where(:role => [User.roles[:doctor], User.roles[:admin]]), :id, :name, :prompt => 'Please select doctor', class: "form-control") %>
      </div>
      <div class="field">
        <%= f.label :reminder_of_appointment %><br>
        <%= f.text_field :reminder_of_appointment, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :reason_for_visit %><br>
        <%= f.text_field :reason_for_visit, class: "form-control" %>
      </div>
    <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appointments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date of visit</th>
      <th>Pet Name</th>
      <th>Customer Name</th>
      <th>Doctor Name</th>
      <th>Reminder of appointment</th>
      <th>Reason for visit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date_of_visit %></td>
        <td><%= appointment.pet.name_of_pet %></td>
        <td><%= appointment.customer.name %></td>
        <td><%= appointment.doctor.name %></td>
        <td><%= appointment.reminder_of_appointment %></td>
        <td><%= appointment.reason_for_visit %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of visit:</strong>
  <%= @appointment.date_of_visit %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @appointment.pet_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @appointment.user_id %>
</p>

<p>
  <strong>Reminder of appointment:</strong>
  <%= @appointment.reminder_of_appointment %>
</p>

<p>
  <strong>Reason for visit:</strong>
  <%= @appointment.reason_for_visit %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Veterinary Practice" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Pundit" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="container">
    <section>
      <div class="page-header">
        <h3 class="pull-left">
          Veterinary Practice:
          <% if user_signed_in? %>
          <span> <%= current_user.name %>(<%= current_user.role %>)</span>
          <% end %>
        </h3>
        <div class="pull-right">
          <div class="btn-group">
              <% if user_signed_in? %>
                   <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', :class => "btn btn-primary"  %>
              <% else %>
                    <%= link_to 'Sign in', new_user_session_path, :class => "btn btn-primary" %>
              <% end %>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
       <%= yield %>
    </section>
  </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_of_pet %><br>
    <%= f.text_field :name_of_pet, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :type_of_pet %><br>
    <%= f.text_field :type_of_pet, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :date_of_last_visit %><br>
    <%= f.date_select :date_of_last_visit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <% if current_user.customer? %>
      <thead>
        <tr>
          <th>Name of pet</th>
          <th>Date of Next Appointment</th>
          <th>Reason for Visit</th>
        </tr>
      </thead>

      <tbody>
        <% @pets.each do |pet| %>
          <tr>
            <td><%= pet.name_of_pet %></td>
            <td><%= pet.appointment.date_of_visit %></td>
            <td><%= pet.appointment.reason_for_visit %></td>
          </tr>
        <% end %>
      </tbody>
  <% else %>
      <thead>
          <tr>
            <th>Name of pet</th>
            <th>Type of Pet</th>
            <th>Breed</th>
            <th>Age</th>
            <th>weight</th>
            <th>Date of Last Visit</th>
            <th></th>
          </tr>
      </thead>

      <tbody>
      <% @pets.each do |pet| %>
          <tr>
            <td><%= pet.name_of_pet %></td>
            <td><%= pet.type_of_pet %></td>
            <td><%= pet.breed %></td>
            <td><%= pet.age %></td>
            <td><%= pet.weight %></td>
            <td><%= pet.date_of_last_visit %></td>
            <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
          </tr>
      <% end %>
      </tbody>
  <% end %>
</table>

<br>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name of pet:</strong>
  <%= @pet.name_of_pet %>
</p>

<p>
  <strong>Type of pet:</strong>
  <%= @pet.type_of_pet %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pet.weight %>
</p>

<p>
  <strong>Date of last visit:</strong>
  <%= @pet.date_of_last_visit %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Role</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>School Received Degree From</th>
    <th>Years in Practice</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.address %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.zip %></td>
        <td><%= user.school_received_degree_from %></td>
        <td><%= user.years_in_practice %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>zip:</strong>
  <%= @user.zip %>
</p>

<p>
  <strong>School Received Degree From:</strong>
  <%= @user.school_received_degree_from %>
</p>

<p>
  <strong>Years in Practice:</strong>
  <%= @user.years_in_practice %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/visitors/index.html.erb
<h3>Welcome</h3>